### ISSUE TITLE
outer / inner scope

### ISSUE THREAD

**Issue by mynameisvinn** [biancasubion/jupyshare#1]
friendly feedback.

you should rename either your (a) parser function (line 13) or (b) local var parser (line 14). otherwise youll have a local/global conflict with the name "parser".

the local name takes precedence so it isnt an issue here, but it would confusing to others!

finally, you should usually change the local name in this case. local/inner scope means it is safe to change.

**Comment by beacoding** [comment]
thanks for catching this!
