### ISSUE TITLE
No token?

### ISSUE THREAD

**Issue by mxmeier** [biancasubion/jupyshare#4]
Hi,

when Im trying to use jupyshare release there are no tokens, there are just ports and paths.
The parsed `x` is just ['8888/ :: /path/to/somewhere\n', '8889/ :: /path/to/somewhere/else\n'].

Do you have an idea what might go wrong here? (I tried using python 2.7 and python 3.5, and Im on OSX Yosemite)

**Comment by beacoding** [comment]
Hey could you tell me what it says when you type in `jupyter notebook list`?

**Comment by mxmeier** [comment]
`>>> jupyter-notebook list`
Currently running servers:
http://localhost:8888/ :: /path/to/somewhere
http://localhost:8889/ :: /path/to/somewhere/else

**Comment by beacoding** [comment]
(Away from my computer for most of the day. I'm sorry ): I'll get back to you as soon as I can though) in the meantime normally Jupyter notebook list shows tokens. What version of Jupyter are you on?

**Comment by mxmeier** [comment]
I was on version 4.2.0, I updated my jupyter to 4.3.0. Now everything works fine, thanks!
